# -*- coding: utf-8 -*-
"""Final automate_Asyifa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojOlcFmRy9zWKg_lbqSkkM9wBqmKnqZH

##**Import Library & Konfigurasi Path**
"""

import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler, LabelEncoder

"""##**Fungsi Load & Clean Data**"""

class DataPreprocessor:
    def __init__(self):
        self.target_col = "Sleep Disorder"
        self.scaler = StandardScaler()
        self.label_encoders = {}
        self.target_encoder = LabelEncoder()

    def load_data(self, filepath):
        self.data = pd.read_csv(filepath)
        print(f"[INFO] Data dimuat. Shape awal: {self.data.shape}")
        return self.data

    def handle_missing_values(self):
        # sama seperti eksperimenmu: dropna
        initial_rows = self.data.shape[0]
        self.data.dropna(inplace=True)
        dropped = initial_rows - self.data.shape[0]
        print(f"[STEP 1] Baris missing dihapus: {dropped}")
        return self.data

    def encode_categorical(self):
        # 1) auto-detect kategori (dtype object)
        categorical_cols = self.data.select_dtypes(include=["object"]).columns.tolist()

        # 2) exclude target dari fitur kategorikal
        if self.target_col in categorical_cols:
            categorical_cols.remove(self.target_col)

        # 3) label encoding fitur kategorikal
        for col in categorical_cols:
            le = LabelEncoder()
            self.data[col] = le.fit_transform(self.data[col])
            self.label_encoders[col] = le
            print(f"[STEP 2] Label Encoding fitur: {col}")

        # 4) label encoding target khusus
        self.data[self.target_col] = self.target_encoder.fit_transform(
            self.data[self.target_col]
        )
        print(f"[STEP 2] Label Encoding target: {self.target_col}")

        return self.data

    def scale_numeric(self):
        # 5) auto-detect numerik (int/float)
        numeric_cols = self.data.select_dtypes(include=["int64", "float64"]).columns.tolist()

        # 6) pastikan target gak ikut scaling
        numeric_cols = [c for c in numeric_cols if c != self.target_col]

        # 7) scaling numerik
        self.data[numeric_cols] = self.scaler.fit_transform(self.data[numeric_cols])
        print(f"[STEP 3] Scaling numerik: {numeric_cols}")

        return self.data

    def save_artifacts(self):
        with open("label_encoders.pkl", "wb") as f:
            pickle.dump(self.label_encoders, f)
        with open("scaler.pkl", "wb") as f:
            pickle.dump(self.scaler, f)
        with open("target_encoder.pkl", "wb") as f:
            pickle.dump(self.target_encoder, f)
        print("[INFO] Artifacts disimpan.")

    def save_data(self, output_filepath):
        self.data.to_csv(output_filepath, index=False)
        print(f"[INFO] Data bersih disimpan ke: {output_filepath}")

    def run(self, input_filepath, output_filepath):
        print("--- MEMULAI PIPELINE AUTOMASI (REPLIKA EKSPERIMEN) ---")
        self.load_data(input_filepath)
        self.handle_missing_values()
        self.encode_categorical()
        self.scale_numeric()
        self.save_artifacts()
        self.save_data(output_filepath)
        print("--- SELESAI ---")

"""##**Fungsi Preprocessing (Encoding & Scaling)**"""

INPUT_FILE = "Sleep_health_and_lifestyle_dataset.csv"
OUTPUT_FILE = "data_bersih_automasi.csv"

preprocessor = DataPreprocessor()
preprocessor.run(INPUT_FILE, OUTPUT_FILE)

df_clean = pd.read_csv(OUTPUT_FILE)
df_clean.head()
